name: Public Nuget Publish

on:
  workflow_dispatch: # Allow running the workflow manually from the GitHub UI
  # push:
  #   branches: [ "releases" ]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v5
    - name: Setup .NET
      uses: actions/setup-dotnet@v5
      with:
        dotnet-version: 9.0.x
      
    - name: Restore dependencies
      run: dotnet restore ./Robin.slnx
      
    - name: Build
      run: dotnet build ./Robin.slnx --configuration Release --no-restore
    
    - name: Test
      run: dotnet test ./Robin.slnx --verbosity normal
    
    - name: Pack
      run: dotnet pack ./Robin.slnx --configuration Release -o ./nupkgs
      
    - name: Push
      run: dotnet nuget push ./nupkgs/*.nupkg --api-key "${{ secrets.PUBLIC_NUGET_TOKEN }}" --source https://api.nuget.org/v3/index.json --skip-duplicate
